StylesPath = .vale/styles
MinAlertLevel = suggestion
Vocab = feedpaper

Packages = Google

[*.md]
BasedOnStyles = Vale, Google

# "chapter" is the correct term for ePub sections in an ebook, so allow it.
Google.WordListCase = NO
